package com.proyecto.entidades;
// Generated 23/06/2018 11:28:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int codigofactura;
     private Cliente cliente;
     private Vendedor vendedor;
     private Integer numerofactura;
     private BigDecimal totalventa;
     private Date fecharegistro;
     private Set<Detallefactura> detallefacturas = new HashSet<Detallefactura>(0);

    public Factura() {
    }

	
    public Factura(int codigofactura) {
        this.codigofactura = codigofactura;
    }
    public Factura(int codigofactura, Cliente cliente, Vendedor vendedor, Integer numerofactura, BigDecimal totalventa, Date fecharegistro, Set<Detallefactura> detallefacturas) {
       this.codigofactura = codigofactura;
       this.cliente = cliente;
       this.vendedor = vendedor;
       this.numerofactura = numerofactura;
       this.totalventa = totalventa;
       this.fecharegistro = fecharegistro;
       this.detallefacturas = detallefacturas;
    }
   
    public int getCodigofactura() {
        return this.codigofactura;
    }
    
    public void setCodigofactura(int codigofactura) {
        this.codigofactura = codigofactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public Integer getNumerofactura() {
        return this.numerofactura;
    }
    
    public void setNumerofactura(Integer numerofactura) {
        this.numerofactura = numerofactura;
    }
    public BigDecimal getTotalventa() {
        return this.totalventa;
    }
    
    public void setTotalventa(BigDecimal totalventa) {
        this.totalventa = totalventa;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Set<Detallefactura> getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set<Detallefactura> detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


