package com.proyecto.entidades;
// Generated 23/06/2018 11:28:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int codigoproducto;
     private String nombre;
     private BigDecimal precioventa;
     private Integer stockminimo;
     private Integer stockactual;
     private String codigobarra;
     private Set<Detallefactura> detallefacturas = new HashSet<Detallefactura>(0);

    public Producto() {
    }

	
    public Producto(int codigoproducto) {
        this.codigoproducto = codigoproducto;
    }
    public Producto(int codigoproducto, String nombre, BigDecimal precioventa, Integer stockminimo, Integer stockactual, String codigobarra, Set<Detallefactura> detallefacturas) {
       this.codigoproducto = codigoproducto;
       this.nombre = nombre;
       this.precioventa = precioventa;
       this.stockminimo = stockminimo;
       this.stockactual = stockactual;
       this.codigobarra = codigobarra;
       this.detallefacturas = detallefacturas;
    }
   
    public int getCodigoproducto() {
        return this.codigoproducto;
    }
    
    public void setCodigoproducto(int codigoproducto) {
        this.codigoproducto = codigoproducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecioventa() {
        return this.precioventa;
    }
    
    public void setPrecioventa(BigDecimal precioventa) {
        this.precioventa = precioventa;
    }
    public Integer getStockminimo() {
        return this.stockminimo;
    }
    
    public void setStockminimo(Integer stockminimo) {
        this.stockminimo = stockminimo;
    }
    public Integer getStockactual() {
        return this.stockactual;
    }
    
    public void setStockactual(Integer stockactual) {
        this.stockactual = stockactual;
    }
    public String getCodigobarra() {
        return this.codigobarra;
    }
    
    public void setCodigobarra(String codigobarra) {
        this.codigobarra = codigobarra;
    }
    public Set<Detallefactura> getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set<Detallefactura> detallefacturas) {
        this.detallefacturas = detallefacturas;
    }

    @Override
    public String toString() {
        return "Producto{" + "codigoproducto=" + codigoproducto + ", nombre=" + nombre + ", precioventa=" + precioventa + ", stockminimo=" + stockminimo + ", stockactual=" + stockactual + ", codigobarra=" + codigobarra + '}';
    }




}


