package com.proyecto.entidades;
// Generated 23/06/2018 11:28:12 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int codigousuario;
     private Vendedor vendedor;
     private String nombre;
     private String password;

    public Usuario() {
    }

	
    public Usuario(int codigousuario) {
        this.codigousuario = codigousuario;
    }
    public Usuario(int codigousuario, Vendedor vendedor, String nombre, String password) {
       this.codigousuario = codigousuario;
       this.vendedor = vendedor;
       this.nombre = nombre;
       this.password = password;
    }
   
    public int getCodigousuario() {
        return this.codigousuario;
    }
    
    public void setCodigousuario(int codigousuario) {
        this.codigousuario = codigousuario;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


