package com.proyecto.entidades;
// Generated 23/06/2018 11:28:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private int codigovendedor;
     private String nombres;
     private String apellidos;
     private String dni;
     private String celuldar;
     private String direccion;
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Vendedor() {
    }

	
    public Vendedor(int codigovendedor) {
        this.codigovendedor = codigovendedor;
    }
    public Vendedor(int codigovendedor, String nombres, String apellidos, String dni, String celuldar, String direccion, Set<Factura> facturas, Set<Usuario> usuarios) {
       this.codigovendedor = codigovendedor;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.dni = dni;
       this.celuldar = celuldar;
       this.direccion = direccion;
       this.facturas = facturas;
       this.usuarios = usuarios;
    }
   
    public int getCodigovendedor() {
        return this.codigovendedor;
    }
    
    public void setCodigovendedor(int codigovendedor) {
        this.codigovendedor = codigovendedor;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getCeluldar() {
        return this.celuldar;
    }
    
    public void setCeluldar(String celuldar) {
        this.celuldar = celuldar;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    @Override
    public String toString() {
        return "Vendedor{" + "codigovendedor=" + codigovendedor + ", nombres=" + nombres + ", apellidos=" + apellidos + ", dni=" + dni + ", celuldar=" + celuldar + ", direccion=" + direccion + '}';
    }




}


